[build]
  functions = "netlify/functions"
  publish = "backend/public"

[[redirects]]
  # Explicit mapping must come BEFORE the generic /api/* rule
  from = "/api/auth/kakao/login"
  to = "/.netlify/functions/auth-kakao-login"
  status = 200
  force = true

[[redirects]]
  from = "/api/ai/ask"
  to = "/.netlify/functions/ai-ask"
  status = 200
  force = true

[[redirects]]
  from = "/api/ai/status"
  to = "/.netlify/functions/ai-status"
  status = 200
  force = true

[[redirects]]
  from = "/api/admin/*"
  to = "/.netlify/functions/admin/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/market/*"
  to = "/.netlify/functions/market/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/"
  to = "/admin.html"
  status = 200
  force = true

[[redirects]]
from = "/api/auth/kakao/login"
to = "/.netlify/functions/auth-kakao-login"
status = 200
force = true